version: '2.0'
workflow:
  tasks:
    client_1_imports:
      action: civis.workflows.execute
      input:
        workflow_id: 112187
      on-success: create_staging_layer
    client_2_imports:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      on-success: create_staging_layer
    client_3_imports:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      on-success: create_staging_layer
    client_4_imports:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      on-success: create_staging_layer
    client_5_imports:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      on-success: create_staging_layer
    client_6_imports:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      on-success: create_staging_layer
    create_staging_layer:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      on-success: Export_to_Moore_DW
      join: all
    Export_to_Moore_DW:
      action: civis.workflows.execute
      input:
        workflow_id: 0
      join: all
